dev: update playwright version to 1.54.2
This resolves the issue with CI being suddenly broken due to:

SyntaxError: The requested module '@playwright/test' does not provide an export named 'Frame'